Repository collective/plone.app.locales, pull requests merged in 2018-03, with the labels that each got.

#190 Update Brazilian Portuguese translations
  CHANGES.rst
  plone/app/locales/locales/pt_BR/LC_MESSAGES/atcontenttypes.po
  plone/app/locales/locales/pt_BR/LC_MESSAGES/atreferencebrowserwidget.po
  plone/app/locales/locales/pt_BR/LC_MESSAGES/cmfeditions.po
  plone/app/locales/locales/pt_BR/LC_MESSAGES/plone.po
  plone/app/locales/locales/pt_BR/LC_MESSAGES/widgets.po
Labels: 22 status: in-progress, 31 needs: help, 32 needs: review, 41 lvl: easy

#194 update german translations
  docs/terms-de.txt
  plone/app/locales/locales/de/LC_MESSAGES/atcontenttypes.po
  plone/app/locales/locales/de/LC_MESSAGES/cmfeditions.po
  plone/app/locales/locales/de/LC_MESSAGES/cmfplacefulworkflow.po
  plone/app/locales/locales/de/LC_MESSAGES/plone.po
Labels: 04 type: enhancement, 24 status: ready, 32 needs: review

#223 german translations after all the merges
  CHANGES.rst
  docs/terms-de.txt
  plone/app/locales/locales/de/LC_MESSAGES/atcontenttypes.po
  plone/app/locales/locales/de/LC_MESSAGES/atreferencebrowserwidget.po
  plone/app/locales/locales/de/LC_MESSAGES/plone.po
  plone/app/locales/locales/de/LC_MESSAGES/widgets.po
Labels: 04 type: enhancement, 22 status: in-progress, 32 needs: review
